services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - SERVICE_ENV=dev
      - SERVICE_NAME=smart-hub
      - SERVICE_PORT=50051
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DATABASE=smart_hub_db
      - LOG_LEVEL=DEBUG
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - smart-hub-network

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart_hub_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smart-hub-network

volumes:
  postgres_data:

networks:
  smart-hub-network:
    driver: bridge
